"""An interactive claim constellation shared by Home and Platform."""
from html import escape

WORKFLOW = [
 ('Intake & Eligibility Screening','Bring claim information together, review eligibility and validate the qualifying payment amount against relevant benchmarks.','Claims Ingest|Eligibility Engine|QPA Validator',[1,2,3],'Eligibility review and payment analysis','Intake & eligibility'),
 ('Open Negotiation','Connect negotiation documentation with the case timeline, so the next action is clear to your team.','Negotiation Workflow',[4],'Negotiation documents and a case timeline','Open negotiation'),
 ('Federal IDR Filing & Arbitration','Prepare the filing, supporting documents and offer strategy for the selected independent dispute resolution entity.','IDRE Submission|Deadline Sentinel',[5,7],'A filing and supporting evidence packet','Federal IDR'),
 ('Recovery & Reconciliation','Connect recovery reporting and payer performance with the case record, so your team can review outcomes and the next follow-up.','Recovery Analytics',[6],'Recovery reporting and follow-up visibility','Recovery'),
 ('Audit-Ready Document Vault','Keep documents, timestamps and actions together in a connected case record, organized from the start.','Audit Trail|Deadline Sentinel',[8,7],'A traceable history of the case','Audit record'),
]
ROUTES = [
 'M300 178 C218 168 216 83 120 68',
 'M300 178 C387 161 393 91 480 68',
 'M300 178 C390 175 425 235 492 239',
 'M300 178 C320 233 281 267 300 327',
 'M300 178 C225 177 181 229 108 239',
]
PRISM = '''<svg class="px-prism" viewBox="0 0 220 195" fill="none" aria-hidden="true"><defs><linearGradient id="px-crystal-left" x1="110" y1="12" x2="50" y2="166" gradientUnits="userSpaceOnUse"><stop stop-color="#9feeff"/><stop offset=".46" stop-color="#2d8fbe"/><stop offset="1" stop-color="#144e7b"/></linearGradient><linearGradient id="px-crystal-right" x1="180" y1="62" x2="111" y2="177" gradientUnits="userSpaceOnUse"><stop stop-color="#ddfcff"/><stop offset=".35" stop-color="#6bd4e6"/><stop offset="1" stop-color="#247fa8"/></linearGradient><linearGradient id="px-crystal-front" x1="71" y1="104" x2="140" y2="175" gradientUnits="userSpaceOnUse"><stop stop-color="#206a9b"/><stop offset="1" stop-color="#073659"/></linearGradient><radialGradient id="px-pool"><stop stop-color="#5bdcec" stop-opacity=".4"/><stop offset="1" stop-color="#5bdcec" stop-opacity="0"/></radialGradient></defs><ellipse cx="110" cy="168" rx="106" ry="25" fill="url(#px-pool)"/><ellipse cx="110" cy="168" rx="86" ry="18" stroke="#4bacc5" stroke-opacity=".32"/><ellipse cx="110" cy="168" rx="62" ry="12" stroke="#75d4e5" stroke-opacity=".28"/><path d="M110 12 190 145 110 179 30 145Z" fill="url(#px-crystal-left)" stroke="#90def1" stroke-width=".8"/><path d="M110 12 190 145 110 179Z" fill="url(#px-crystal-right)"/><path d="M110 82 190 145 110 179 30 145Z" fill="url(#px-crystal-front)" opacity=".86"/><path d="M110 12V82L30 145M110 82 190 145M110 82V179M30 145 110 124 190 145M110 12 110 179" stroke="#bcf4ff" stroke-opacity=".55" stroke-width=".9"/><path d="M110 12 190 145 110 179" stroke="#d8fcff" stroke-opacity=".8" stroke-width="1.1"/><path d="M86 105 110 94 134 105 110 117Z" fill="#e9fbff" fill-opacity=".91"/><path d="M86 113 110 125 134 113M86 121 110 133 134 121" stroke="#d5faff" stroke-width="1.6" stroke-linecap="round"/><circle cx="110" cy="12" r="2.3" fill="#fff"/></svg>'''

def process_section():
 nodes,panels,paths=[],[],[]
 for i,(name,copy,labels,anchors,outcome,short) in enumerate(WORKFLOW):
  links=''.join(f'<a href="/products/#module-{a}">{escape(label)}<span aria-hidden="true">↗</span></a>' for label,a in zip(labels.split('|'),anchors))
  nodes.append(f'''<button class="px-node" type="button" id="px-stage-{i}" role="tab" aria-label="{escape((short+": "+name) if i==4 else name,quote=True)}" aria-selected="{str(i==0).lower()}" aria-controls="px-panel-{i}" tabindex="{0 if i==0 else -1}" data-px-stage="{i}"><span class="px-node-number" aria-hidden="true">0{i+1}</span><span class="px-node-name">{escape(short)}</span><span class="px-node-light" aria-hidden="true"></span></button>''')
  panels.append(f'''<div class="px-panel" id="px-panel-{i}" role="tabpanel" aria-labelledby="px-stage-{i}" tabindex="0"{' hidden' if i else ''}><div class="px-stage-meta"><span>Stage 0{i+1}</span><span>of 05</span></div><h3>{escape(name)}</h3><p class="px-copy">{escape(copy)}</p><div class="px-output"><span>The output</span><strong>{escape(outcome)}</strong></div><div class="px-modules"><span>Supporting software</span><div>{links}</div></div></div>''')
  paths.append(f'<path class="px-route" data-px-route="{i}" d="{ROUTES[i]}"/>')
 return '''<section class="section px-section" id="process" data-process-experience><div class="container"><div class="section-head px-heading"><div class="eyebrow">The PRISM process</div><div><h2>One case. A connected journey.</h2><p>Explore the stages, specialists and software behind every step.</p></div></div><div class="px-constellation" data-px-active="0"><div class="px-canvas"><div class="px-canvas-heading"><span><i aria-hidden="true"></i>The claim journey</span><span>Select a stage to explore <span aria-hidden="true">↗</span></span></div><div class="px-map"><svg class="px-orbits" viewBox="0 0 600 380" preserveAspectRatio="none" fill="none" aria-hidden="true"><ellipse cx="300" cy="180" rx="247" ry="142" transform="rotate(-12 300 180)" class="px-orbit-back"/><path class="px-orbit" d="M120 68 C215 5 402 0 480 68 C548 120 559 204 492 239 C424 291 373 350 300 327 C218 350 140 293 108 239 C40 203 53 116 120 68Z"/><path class="px-gridline" d="M40 200 555 101M68 295 510 13M131 360 459 13"/>'''+''.join(paths)+'''<path class="px-flow" d="'''+ROUTES[0]+'''"/><g class="px-stars"><circle cx="268" cy="28" r="1.4"/><circle cx="545" cy="176" r="1.4"/><circle cx="420" cy="308" r="1.1"/><circle cx="61" cy="168" r="1.3"/><circle cx="180" cy="305" r="1"/></g></svg><div class="px-hub">'''+PRISM+'''<strong>One connected<br>case record</strong></div><div class="px-nodes" role="tablist" aria-label="Five stages of a claim" data-process-tabs>'''+''.join(nodes)+'''</div></div><p class="px-mobile-caption" aria-hidden="true">One connected case record</p><div class="px-shared-record"><span>At every stage</span><div><a href="/products/#module-7">Deadline Sentinel</a><span aria-hidden="true">·</span><a href="/products/#module-8">Audit Trail</a></div></div></div><div class="px-detail"><div class="px-panels">'''+''.join(panels)+'''</div><div class="px-navigation"><button class="px-tour" type="button" aria-pressed="false"><span class="px-tour-icon" aria-hidden="true">▷</span><span data-px-tour-label>Play the journey</span></button><div class="px-step-controls"><button type="button" class="px-prev" aria-label="Previous stage"><span aria-hidden="true">←</span></button><button type="button" class="px-next" aria-label="Next stage"><span aria-hidden="true">→</span></button></div></div><div class="px-tour-track" aria-hidden="true"><span></span></div></div><span class="px-screen-reader" role="status" aria-live="polite" aria-atomic="true" data-px-status></span></div></div></section>'''
